// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Med_Safe_Net_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250517165813_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid?>("UserCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserCode")
                        .IsUnique()
                        .HasFilter("[UserCode] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DateOfBirth = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            LastName = "User",
                            PasswordHash = new byte[] { 20, 196, 210, 15, 109, 54, 194, 255, 98, 194, 116, 98, 140, 56, 152, 72, 188, 204, 141, 251, 122, 71, 56, 119, 176, 210, 226, 17, 230, 17, 100, 99, 14, 117, 230, 236, 144, 178, 29, 226, 26, 172, 4, 118, 26, 159, 192, 122, 39, 226, 114, 181, 95, 214, 214, 150, 78, 108, 47, 178, 134, 80, 54, 4 },
                            PasswordSalt = new byte[] { 219, 72, 188, 153, 201, 97, 63, 7, 223, 149, 139, 92, 149, 109, 38, 125, 112, 228, 184, 218, 97, 134, 32, 129, 37, 29, 96, 116, 228, 15, 161, 56, 150, 240, 72, 222, 53, 145, 70, 100, 111, 144, 98, 53, 80, 66, 132, 151, 195, 19, 54, 179, 174, 54, 134, 252, 23, 133, 95, 56, 161, 57, 248, 45, 27, 231, 194, 246, 132, 181, 46, 109, 110, 85, 90, 66, 145, 77, 120, 44, 142, 240, 207, 248, 203, 254, 158, 127, 20, 238, 216, 219, 97, 245, 65, 18, 223, 231, 186, 89, 233, 181, 154, 112, 76, 83, 59, 154, 183, 255, 3, 87, 187, 64, 75, 142, 72, 28, 13, 92, 252, 150, 94, 118, 185, 45, 167, 11 },
                            UserCode = new Guid("9d7ec4b8-4a55-41e5-a5ce-c06e8de95b2c"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = -2,
                            DateOfBirth = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cg1@example.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            PasswordHash = new byte[] { 20, 196, 210, 15, 109, 54, 194, 255, 98, 194, 116, 98, 140, 56, 152, 72, 188, 204, 141, 251, 122, 71, 56, 119, 176, 210, 226, 17, 230, 17, 100, 99, 14, 117, 230, 236, 144, 178, 29, 226, 26, 172, 4, 118, 26, 159, 192, 122, 39, 226, 114, 181, 95, 214, 214, 150, 78, 108, 47, 178, 134, 80, 54, 4 },
                            PasswordSalt = new byte[] { 219, 72, 188, 153, 201, 97, 63, 7, 223, 149, 139, 92, 149, 109, 38, 125, 112, 228, 184, 218, 97, 134, 32, 129, 37, 29, 96, 116, 228, 15, 161, 56, 150, 240, 72, 222, 53, 145, 70, 100, 111, 144, 98, 53, 80, 66, 132, 151, 195, 19, 54, 179, 174, 54, 134, 252, 23, 133, 95, 56, 161, 57, 248, 45, 27, 231, 194, 246, 132, 181, 46, 109, 110, 85, 90, 66, 145, 77, 120, 44, 142, 240, 207, 248, 203, 254, 158, 127, 20, 238, 216, 219, 97, 245, 65, 18, 223, 231, 186, 89, 233, 181, 154, 112, 76, 83, 59, 154, 183, 255, 3, 87, 187, 64, 75, 142, 72, 28, 13, 92, 252, 150, 94, 118, 185, 45, 167, 11 },
                            UserCode = new Guid("6571d10f-90b1-4785-b151-fb908cdb6e34"),
                            Username = "caregiver1"
                        },
                        new
                        {
                            Id = -3,
                            DateOfBirth = new DateTime(1992, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cg2@example.com",
                            FirstName = "Bob",
                            LastName = "Johnson",
                            PasswordHash = new byte[] { 20, 196, 210, 15, 109, 54, 194, 255, 98, 194, 116, 98, 140, 56, 152, 72, 188, 204, 141, 251, 122, 71, 56, 119, 176, 210, 226, 17, 230, 17, 100, 99, 14, 117, 230, 236, 144, 178, 29, 226, 26, 172, 4, 118, 26, 159, 192, 122, 39, 226, 114, 181, 95, 214, 214, 150, 78, 108, 47, 178, 134, 80, 54, 4 },
                            PasswordSalt = new byte[] { 219, 72, 188, 153, 201, 97, 63, 7, 223, 149, 139, 92, 149, 109, 38, 125, 112, 228, 184, 218, 97, 134, 32, 129, 37, 29, 96, 116, 228, 15, 161, 56, 150, 240, 72, 222, 53, 145, 70, 100, 111, 144, 98, 53, 80, 66, 132, 151, 195, 19, 54, 179, 174, 54, 134, 252, 23, 133, 95, 56, 161, 57, 248, 45, 27, 231, 194, 246, 132, 181, 46, 109, 110, 85, 90, 66, 145, 77, 120, 44, 142, 240, 207, 248, 203, 254, 158, 127, 20, 238, 216, 219, 97, 245, 65, 18, 223, 231, 186, 89, 233, 181, 154, 112, 76, 83, 59, 154, 183, 255, 3, 87, 187, 64, 75, 142, 72, 28, 13, 92, 252, 150, 94, 118, 185, 45, 167, 11 },
                            UserCode = new Guid("0312b76d-6351-4b5a-bc41-00f69e21f6e0"),
                            Username = "caregiver2"
                        },
                        new
                        {
                            Id = -4,
                            DateOfBirth = new DateTime(1952, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "patient@example.com",
                            FirstName = "Eve",
                            LastName = "Doe",
                            PasswordHash = new byte[] { 20, 196, 210, 15, 109, 54, 194, 255, 98, 194, 116, 98, 140, 56, 152, 72, 188, 204, 141, 251, 122, 71, 56, 119, 176, 210, 226, 17, 230, 17, 100, 99, 14, 117, 230, 236, 144, 178, 29, 226, 26, 172, 4, 118, 26, 159, 192, 122, 39, 226, 114, 181, 95, 214, 214, 150, 78, 108, 47, 178, 134, 80, 54, 4 },
                            PasswordSalt = new byte[] { 219, 72, 188, 153, 201, 97, 63, 7, 223, 149, 139, 92, 149, 109, 38, 125, 112, 228, 184, 218, 97, 134, 32, 129, 37, 29, 96, 116, 228, 15, 161, 56, 150, 240, 72, 222, 53, 145, 70, 100, 111, 144, 98, 53, 80, 66, 132, 151, 195, 19, 54, 179, 174, 54, 134, 252, 23, 133, 95, 56, 161, 57, 248, 45, 27, 231, 194, 246, 132, 181, 46, 109, 110, 85, 90, 66, 145, 77, 120, 44, 142, 240, 207, 248, 203, 254, 158, 127, 20, 238, 216, 219, 97, 245, 65, 18, 223, 231, 186, 89, 233, 181, 154, 112, 76, 83, 59, 154, 183, 255, 3, 87, 187, 64, 75, 142, 72, 28, 13, 92, 252, 150, 94, 118, 185, 45, 167, 11 },
                            UserCode = new Guid("77fa3ba7-1a22-4fd4-8dce-28839ec9aab0"),
                            Username = "patient1"
                        },
                        new
                        {
                            Id = -5,
                            DateOfBirth = new DateTime(1962, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "patient2@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = new byte[] { 20, 196, 210, 15, 109, 54, 194, 255, 98, 194, 116, 98, 140, 56, 152, 72, 188, 204, 141, 251, 122, 71, 56, 119, 176, 210, 226, 17, 230, 17, 100, 99, 14, 117, 230, 236, 144, 178, 29, 226, 26, 172, 4, 118, 26, 159, 192, 122, 39, 226, 114, 181, 95, 214, 214, 150, 78, 108, 47, 178, 134, 80, 54, 4 },
                            PasswordSalt = new byte[] { 219, 72, 188, 153, 201, 97, 63, 7, 223, 149, 139, 92, 149, 109, 38, 125, 112, 228, 184, 218, 97, 134, 32, 129, 37, 29, 96, 116, 228, 15, 161, 56, 150, 240, 72, 222, 53, 145, 70, 100, 111, 144, 98, 53, 80, 66, 132, 151, 195, 19, 54, 179, 174, 54, 134, 252, 23, 133, 95, 56, 161, 57, 248, 45, 27, 231, 194, 246, 132, 181, 46, 109, 110, 85, 90, 66, 145, 77, 120, 44, 142, 240, 207, 248, 203, 254, 158, 127, 20, 238, 216, 219, 97, 245, 65, 18, 223, 231, 186, 89, 233, 181, 154, 112, 76, 83, 59, 154, 183, 255, 3, 87, 187, 64, 75, 142, 72, 28, 13, 92, 252, 150, 94, 118, 185, 45, 167, 11 },
                            UserCode = new Guid("657bbfc8-37ae-41b6-b602-103832142593"),
                            Username = "patient2"
                        });
                });

            modelBuilder.Entity("API.Entities.HeartRate", b =>
                {
                    b.Property<int>("HeartRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Measurement")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeartRateId");

                    b.HasIndex("UserId");

                    b.ToTable("HeartRates");
                });

            modelBuilder.Entity("API.Entities.HighHeartRate", b =>
                {
                    b.Property<int>("HighHeartRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Confirm")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Measurement")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("TimeOfConfirmation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HighHeartRateId");

                    b.HasIndex("UserId");

                    b.ToTable("HighHeartRates");
                });

            modelBuilder.Entity("API.Entities.SuddenMovement", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Confirm")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimeOfConfirmation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovementId");

                    b.HasIndex("UserId");

                    b.ToTable("SuddenMovements");
                });

            modelBuilder.Entity("Med_Safe_Net_API.Entities.AppRole", b =>
                {
                    b.Property<int>("AppRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppRoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppRoleId");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            AppRoleId = 3,
                            AppRoleName = "Administrator"
                        },
                        new
                        {
                            AppRoleId = 2,
                            AppRoleName = "Caregiver"
                        },
                        new
                        {
                            AppRoleId = 1,
                            AppRoleName = "Patient"
                        });
                });

            modelBuilder.Entity("Med_Safe_Net_API.Entities.UserLink", b =>
                {
                    b.Property<int>("UserLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CareGiverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserLinkId");

                    b.HasIndex("CareGiverId");

                    b.HasIndex("PatientId", "CareGiverId")
                        .IsUnique();

                    b.ToTable("UserLinks");

                    b.HasData(
                        new
                        {
                            UserLinkId = -1,
                            CareGiverId = -2,
                            PatientId = -4
                        },
                        new
                        {
                            UserLinkId = -2,
                            CareGiverId = -3,
                            PatientId = -4
                        },
                        new
                        {
                            UserLinkId = -3,
                            CareGiverId = -2,
                            PatientId = -5
                        },
                        new
                        {
                            UserLinkId = -4,
                            CareGiverId = -1,
                            PatientId = -4
                        },
                        new
                        {
                            UserLinkId = -5,
                            CareGiverId = -1,
                            PatientId = -5
                        });
                });

            modelBuilder.Entity("Med_Safe_Net_API.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserRoleId");

                    b.HasIndex("AppRoleId");

                    b.HasIndex("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleId = -1,
                            AppRoleId = 3,
                            Id = -1
                        },
                        new
                        {
                            UserRoleId = -2,
                            AppRoleId = 2,
                            Id = -2
                        },
                        new
                        {
                            UserRoleId = -3,
                            AppRoleId = 2,
                            Id = -3
                        },
                        new
                        {
                            UserRoleId = -4,
                            AppRoleId = 1,
                            Id = -4
                        },
                        new
                        {
                            UserRoleId = -5,
                            AppRoleId = 1,
                            Id = -5
                        });
                });

            modelBuilder.Entity("API.Entities.HeartRate", b =>
                {
                    b.HasOne("API.Entities.AppUser", "User")
                        .WithMany("HeartRates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Entities.HighHeartRate", b =>
                {
                    b.HasOne("API.Entities.AppUser", "User")
                        .WithMany("HighHeartRates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Entities.SuddenMovement", b =>
                {
                    b.HasOne("API.Entities.AppUser", "User")
                        .WithMany("SuddenMovements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Med_Safe_Net_API.Entities.UserLink", b =>
                {
                    b.HasOne("API.Entities.AppUser", "CareGiver")
                        .WithMany("UserLinks")
                        .HasForeignKey("CareGiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.AppUser", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareGiver");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Med_Safe_Net_API.Entities.UserRole", b =>
                {
                    b.HasOne("Med_Safe_Net_API.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Navigation("HeartRates");

                    b.Navigation("HighHeartRates");

                    b.Navigation("SuddenMovements");

                    b.Navigation("UserLinks");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Med_Safe_Net_API.Entities.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
